Revert "Add fallback to bswap_16 for gcc on Windows (closes #377)"
This reverts commit 1d3c6401f8186b54453ba64606758a90b6ec3fca.

TravisCI reports:
../src/.libs/libmodbus.so: undefined reference to `__builtin_bswap16'

with gcc 4.6.3